### ISSUE TITLE
"Could not find electron"

### ISSUE THREAD

**Issue by aredfox** [bjrmatos/electron-workers#267]
When packaging with electron-builder, the application says it could not find electron.
I see i your docs the following:

> pathToElectron - path to the electron executable, by default we will try to find the path using the value returned from electron-prebuilt or the value in your $PATH.

But do I have to include "electron" in the dependencies then in stead of the devDependencies. How would I search for the electron executable path myself to pass it to pathToElectron. Or do my clients need to have electron installed globally, or somewhere via the installer I provide? I'm kind of lost here on how to solve this?

Note, when developping it works fine, it's only when it's packaged.

**Comment by bjrmatos** [comment]
> When packaging with electron-builder, the application says it could not find electron.

hmm, `electron-workers` is designed to be called from nodejs (a nodejs process), are you calling it from an electron app (electron process)?

> But do I have to include "electron" in the dependencies then in stead of the devDependencies.

at the time of building this package the only way to install the `electron` executable from npm was using the [electron-prebuilt](https://www.npmjs.com/package/electron-prebuilt) package.

now there is also the [electron](https://www.npmjs.com/package/electron) package (it is just the `electron-prebuilt` package published with the name `electron`), so i think that the issue can be solved searching for both packages  (`electron` and the `electron-prebuilt` package). 

Let me try it.


> How would I search for the electron executable path myself to pass it to pathToElectron.

you can require the `electron` package from node and get the path to the executable.

```js
var electron = require('electron')
 
// will print something similar to /Users/maf/.../Electron (path to the electron executable) 
console.log(electron);
```

**Comment by sklink** [comment]
I'm having this same issue with the workers.

It didn't work by default, giving me this error: 

```
{ Error: electron manager could not start all workers..
    at startHandler (D:\dev\becomethegamer\overlay\node_modules\electron-workers\lib\ElectronManager.js:169:37)
    at ElectronWorker._this2._handleSpawnError (D:\dev\becomethegamer\overlay\node_modules\electron-workers\lib\ElectronWorker.js:281:11)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:101:20)
    at ChildProcess.emit (events.js:188:7)
    at Module.runMain (module.js:607:11)
  workerErrors:
   [ { Error: spawn D:\dev\becomethegamer\overlay\app\node_modules\electron\dist\electron.exe ENOENT
         at exports._errnoException (util.js:1022:11)
         at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       code: 'ENOENT',
       errno: 'ENOENT',
       syscall: 'spawn D:\\dev\\becomethegamer\\overlay\\app\\node_modules\\electron\\dist\\electron.exe',
       path: 'D:\\dev\\becomethegamer\\overlay\\app\\node_modules\\electron\\dist\\electron.exe',
       spawnargs: [Object] } ] }
webpack: wait until bundle finished: /dist/bundle.js
```

After that I was able to get it to work by adding `pathToElectron` to the electron worker settings:

```
electronWorkers({
  connectionMode: 'ipc',
  pathToScript: './app/services/capture.js',
  timeout: 5000,
  numberOfWorkers: 1,
  pathToElectron: path.join(global.currPath, '/node_modules/electron/dist/electron.exe')
});
```

However, when I compiled the app with `electron-builder`, the `/node_modules/electron/dist/electron.exe` was no longer available because `electron` is installed as a `devDependency`.

Electron Builder does not allow `electron` or `electron-prebuilt` to be installed anywhere other than under `devDependencies`:

```
Error: Package "electron-prebuilt" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.
    at checkDependencies (D:\dev\becomethegamer\overlay\node_modules\electron-builder\src\packager.ts:329:13)
    at Packager.checkMetadata (D:\dev\becomethegamer\overlay\node_modules\electron-builder\src\packager.ts:189:7)
    at D:\dev\becomethegamer\overlay\node_modules\electron-builder\src\packager.ts:93:10
```

When I `console.log(electron)` it gives me a list of all of the functions, rather than the path, so I was unable to properly test that out either.

How would you suggest going about this?

**Comment by bjrmatos** [comment]
@sklink hmm seems like you are trying to execute `electron-workers` from your electron app.. 

have in mind that `electron-workers` is designed to called from a **node.js app** not directly from a `electron app`, `electron-workers` spawns new electron processes (that is why it requires electron to be installed) and delegate tasks to those processes.

i'm curious to know, in what part of your electron app you are using `electron-workers`?

**Comment by sklink** [comment]
From the main process. Problem with running it separately is that I need to package the application and allow my users to install it. I may have assumed this was created for a purpose it wasn't meant for though.

I was able to move my code into the main process rather than using the workers just fine.

**Comment by bjrmatos** [comment]
👌 yes, it was created for the purpose of managing electron processes and do some tasks in the workers (like creating pdf, images or anything that electron can do) but from a node.js app, it is like a pool of electron processes waiting for some tasks, the tasks are sent from a node.js app.

closing the issue now because it seems like it is just a misunderstanding about the usage of the package
