### ISSUE TITLE
TypeError: Bad argument (bad electron path)

### ISSUE THREAD

**Issue by patrickhulce** [bjrmatos/electron-workers#286]
When trying to use electron-workers I get an uncaught promise rejection that traces back to the `spawn` call.

**Usage**

```js
const workers = require('electron-workers')({connectionMode: 'ipc'})
workers.start(console.log)
TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:399:9)
    at /Users/patrick/Code/.../node_modules/electron-workers/lib/ElectronWorker.js:277:57
    at ElectronWorker.findFreePort (/Users/patrick/Code/.../node_modules/electron-workers/lib/ElectronWorker.js:122:9)
    at ElectronWorker.start 
```

looking at the code I'm not sure how it could possibly be working for everyone, so there must be something I'm missing :)

The error comes about because the path that's being passed to spawn is an object and not a string,
 [this line](https://github.com/bjrmatos/electron-workers/blob/master/src/ElectronManager.js#L63) returns the electron module itself, not the path to the electron binary. Indeed manually passing in the electron binary `node_modules/electron/dist/Electron.app/Contents/MacOS/Electron` fixes the issue, but I then run into several new bugs I can report separately once this is cleared up.

**Comment by bjrmatos** [comment]
it seems to me that you are trying to use the package from an electron process/app. there is other issue with a similar problem where i've made some [comments about running this package from an electron app](https://github.com/bjrmatos/electron-workers/issues/267) 

this package has been designed to be used from a node.js process/app to manage a pool of electron processes, if you use this package from a node.js process and you require the [npm electron/electron-prebuilt package](https://github.com/electron-userland/electron-prebuilt) 
 with `require('electron')`  [it will return a string](https://github.com/electron-userland/electron-prebuilt#programmatic-usage) (not an object).. your issue is that you are trying to execute this package from an electron process in which `require('electron')` returns an object.

i've never have the need to execute this package from an electron process so if you have that requirement you can start a PR to support that case and i will take a look 👍
